// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramacionIVAPI;

#nullable disable

namespace ProgramacionIVAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231016123859_productos")]
    partial class productos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramacionIV.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Cantidad = 23,
                            Descripcion = "D1",
                            Nombre = "P1"
                        },
                        new
                        {
                            IdProducto = 2,
                            Cantidad = 12,
                            Descripcion = "D2",
                            Nombre = "P2"
                        },
                        new
                        {
                            IdProducto = 4,
                            Cantidad = 76,
                            Descripcion = "D3",
                            Nombre = "P3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
